services:
  www:
    build:
      context: .
      target: prod
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mariadb:11
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306

volumes:
  db: