ServerTokens Prod
ServerSignature Off
TraceEnable Off
Header unset X-Powered-By
Header set X-Content-Type-Options "nosniff"
Header set Content-Security-Policy "default-src 'self'; img-src 'self' data: https://photos.szukajwarchiwach.gov.pl https://metbox3.genealodzy.pl; script-src 'self' https://stackpath.bootstrapcdn.com 'unsafe-inline'; style-src 'self' https://stackpath.bootstrapcdn.com 'unsafe-inline'; base-uri 'none'; frame-src 'none'; frame-ancestors 'none'; connect-src 'self' https://stackpath.bootstrapcdn.com"